site_name: CONCORD - Contrastive Learning for Cross-domain Reconciliation and Discovery
theme:
  name: material
  logo: 'images/logo.png'
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - toc.integrate
    - navigation.top
    - navigation.sticky
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - navigation.expand
    - navigation.mobile
    - navigation.instant
    - content.full_width
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      accent: lime

nav:
  - Getting started: index.md
  - Galleries: 
    - Intestine development Atlas: galleries/huycke_show.md
    - C.elegans/C.briggsae Embryogenesis Atlas: galleries/cbce_show.md
  - Tutorials: 
    - Single batch, RNA-seq:
      - PBMC3k dataset, single batch: notebooks/concord_pbmc3k.ipynb
    - Multiple batch, RNA-seq:
      - Intestine development by Huycke et al.: notebooks/concord_Huycke.ipynb
      - Mouse organogenesis (100k cell subset) by Cao et al.: notebooks/concord_mouse_organogenesis_100k.ipynb
  - Advanced usage: 
    - Simulation pipeline: 
      - Trajectory simulation: notebooks/simulation_trajectory_show.ipynb
  - API: 
    - Concord: api/main.md
    - Model: api/model.md
    - Utility: api/utils.md
    - Plotting: api/plotting.md
  - About:
    - Citation & Feedback: about.md
    - License: LICENSE.md

plugins:
  - social
  - search
  - mkdocs-jupyter:
      include_source: True
      include_requirejs: True
  - mkdocstrings:
      handlers:
        python:
          paths: ["../Concord"]
          options:
            show_source: false  # Hide source code
            show_root_heading: true
            heading_level: 2
            members_order: alphabetical

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Gartner-Lab/Concord
  include:
    - galleries/

extra_javascript:
  - https://cdn.plot.ly/plotly-2.35.2.min.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: false
      title: "Table of Contents"
      toc_depth: 2 

copyright: |
  &copy; 2025 <a href="https://github.com/Gartner-Lab"  target="_blank" rel="noopener">Gartner Lab</a>